# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: phpunit/phpunit:5.0.3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer --version
          - ls -a
          - phpunit --version
          - phpunit -c tests/phpunit.xml